    - name: Requirements-Playbook
      hosts: ansible_secured_server
      remote_user: "{{ user_name }}"
      vars_files: ./group_vars/variables.yml

      roles:
        - requirements
        - ssh