    - name: update and upgrade
      become: true
      apt:
        update_cache: yes
        upgrade: yes

    - name: install packages
      become: true
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - host
          - kbtin
          - ntp
          - libpam-pwquality
          - unattended-upgrades
          - apt-listchanges
          - apticron
        state: present

    - name: install ufw, psad, fail2ban packages
      become: true
      apt:
        name: 
          - ufw
          - psad
          - fail2ban
        state: present

    - name: accept msmtp AppArmor before installing
      become: true
      ansible.builtin.debconf:
        name: msmtp
        question: msmtp/apparmor
        value: 'true'
        vtype: select

    - name: install mail related packages
      become: true
      apt:
        name: 
          - msmtp
          - msmtp-mta
          - mailutils
        state: present

    - name: Remove mail "bsd-mailx" package
      become: true
      apt:
        name: bsd-mailx
        state: absent

    - name: install rkhunter and clamav antivirus related packages
      become: true
      apt:
        name: 
          - rkhunter
          - clamav
          - clamav-freshclam
          - clamav-daemon
        state: present

    - name: install audit packages
      become: true
      apt:
        name: 
          - auditd
          - audispd-plugins
        state: present
