    - name: update and upgrade
      become: true
      apt:
        update_cache: yes
        upgrade: yes

    - name: Accept msmtp AppArmor before installing
      become: true
      ansible.builtin.debconf:
        name: msmtp
        question: msmtp/apparmor
        value: 'true'
        vtype: select

    - name: install packages
      become: true
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - host
          - kbtin
          - ntp
          - libpam-pwquality
          - unattended-upgrades
          - apt-listchanges
          - apticron
          - ufw
          - psad
          - fail2ban
          - msmtp
          - msmtp-mta
          - mailutils
          - bsd-mailx
          - clamav
          - clamav-freshclam
          - clamav-daemon
          - rkhunter
          - auditd
          - audispd-plugins
        state: present
