    - name: apt update
      become: true
      apt:
        update_cache: yes
        upgrade: false

    - name: create group for ssh users
      become: true
      group:
        name: '{{ sshusers_group }}'

    - name: create group for su users
      become: true
      group:
        name: '{{ suusers_group }}'

    - name: create group for sudo users
      become: true
      group:
        name: '{{ sudousers_group }}'

    - name: update user groups
      become: true
      user:
        name: "{{ user_name }}"
        groups: "{{ sshusers_group }}, {{ sudousers_group }}, {{ suusers_group }}"
        append: true
        shell: /bin/bash

    - name: limit sudo to sudousers groups
      become: true
      lineinfile:
        path: /etc/sudoers
        regexp: '^%{{ sudousers_group }}'
        line: '%{{ sudousers_group }}   ALL=(ALL:ALL) ALL'

    - name: limit who can use su
      become: true
      register: sustd
      shell: |
        sudo dpkg-statoverride --update --add root {{ suusers_group }} 4750 /bin/su
      failed_when: 
        - sustd.rc != 0
        - '"exist" not in sustd.stderr' # this has to be changed: unsure how to skip the "already exist" error in other languages

    - name: passwordless sudo for new user
      become: true
      lineinfile:
        path: /etc/sudoers
        regexp: '^{{ user_name }}'
        line: '{{ user_name }} ALL=(ALL) NOPASSWD: ALL'
        state: present
        mode: 0440
        create: yes
        validate: 'visudo -cf %s'
      when: passwordless_sudo == true

    - name: add authorized keys for new user
      become: true
      authorized_key:
        user: "{{ user_name }}"
        key: "{{ lookup('file', sshpub_location) }}"
