
    - name: configure mail settings
      become: true
      blockinfile:
        path: /etc/msmtprc
        block: |
          defaults
          port {{ mail_port }}
          tls on
          tls_trust_file /etc/ssl/certs/ca-certificates.crt
          account email
          host {{ mail_smtp_server }}
          set_from_header on
          from {{ mail_from }}
          auth on
          user {{ mail_username }}
          password {{ mail_pw }}
          account default: email
          aliases /etc/aliases
          logfile /var/log/msmtp
        create: true

    - name: chmod mail config file
      become: true
      file:
        path: /etc/msmtprc
        group: msmtp
        mode: '640'

    - name: add user to mail group
      become: true
      user:
        name: "{{ user_name }}"
        groups: "msmtp"
        append: true

    - name: configure mail settings pt. 2
      become: true
      lineinfile:
        dest: /etc/aliases
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        create: true
      loop:
        - { regexp: '^root:', line: 'root: {{ mail_to }}' }
        - { regexp: '^default:', line: 'default: {{ mail_to }}' }

    - name: configure mail settings pt. 3
      become: true
      lineinfile:
        path: /etc/mail.rc
        line: 'set mta=/usr/bin/msmtp'
        create: yes

    - name: send a testmail
      shell: echo "Testmail content. Success." | mail -s "Testmail subject - ansible playbook" {{ mail_to }}
      #shell: echo "Hello World" | msmtp -d {{ mail_to }}
      #Test sending a mail to root
      #shell: echo "Testing msmtp from ${HOSTNAME} with mail command" | mail -s "hi root" root
      #Test sending a mail to another email adress
      #shell: echo "Testing msmtp from ${HOSTNAME} with mail command" | mail -s "hi there" {{ mail_to }}